server:
  port: 8081  # 解决端口占用问题

# # spring:
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     # 改这里：把 你的数据库名 换成宝塔里你创建的数据库名字
#     # url: jdbc:mysql://localhost:3306/bdis_work?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#     # username: bdis_work
#     # password: 123456
#     url: jdbc:mysql://127.0.0.1:3306/bdis_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#     username: root
#     password: Dy032413

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdis_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: Dy032413
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bdis.bdis_website.entity  # 确保包路径与你的项目一致
  configuration:
    map-underscore-to-camel-case: true
