spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bdis_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bdis.website.entity
  configuration:
    map-underscore-to-camel-case: true